### PR TITLE
update readme and trigger build on travis

### PR DESCRIPTION
**Pull request by dehann**

### CODE REVIEW

**Comment by dehann** [comment]
Hi @rdeits , I'm having difficulties with getting Travis to trigger on this JR repo.  It is similar to `BotCoreLCMTypes.jl`.  Do you maybe have any ideas?  I don't think there are any limits on Travis and an Organization is there?

**Comment by rdeits** [comment]
It should work fine, but I've noticed that I had to turn it off and on again for this repo over at https://travis-ci.org/profile/JuliaRobotics to get travis to notice the new repo. I just did that now, so I'll re-open this PR and see if that worked.

**Comment by rdeits** [comment]
I also made a checklist for myself that you might find helpful: https://github.com/JuliaRobotics/administration/wiki/PackageTransferChecklist

**Comment by rdeits** [comment]
Oh, never mind, there's actually something wrong with your `.travis.yml`. You can see the error message over at https://travis-ci.org/JuliaRobotics/CaesarLCMTypes.jl/requests

**Comment by rdeits** [comment]
fixed in #6

**Comment by dehann** [comment]
Ah man, really, really... I have been over that 10 times. Thanks!

**Comment by dehann** [comment]
all fixed and working now, thanks.

**Pull request merged**
